- hosts: all
  gather_facts: false

# hosts: localhost
# hosts: 127.0.0.1
# hosts: ::1

  tasks:
    - command: hostname
      delegate_to: localhost
      register: out

    - debug:
        var: out.stdout
