- hosts: all
  tasks:
    - include_vars:
        # То же, что vars_files, но можно вызвать в любом месте плейбука,
        # а не только в начале. Плюс есть режим с параметром dir — можно
        # массово загрузить и вывести содержимое ВСЕХ yml/json файлов
        # из указанной директории сервера за один таск.
        file: /etc/ansible/secret.yml